export const ActionsType = {
  FETCH_PRODUCT: "FETCH_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  DEC: "DEC",
  INC: "INC",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
